---
- id: gitlab-codeowners-linter
  name: lint Gitlab's CODEOWNERS file
  description: check that the CODEOWNERS file is well formatted
  entry: gitlab-codeowners-linter
  language: python
  files: ^(CODEOWNERS|.gitlab/CODEOWNERS|docs/CODEOWNERS)
  pass_filenames: false
